# Generated by Django 4.0.6 on 2022-08-15 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('container_size', models.CharField(choices=[('20', '20'), ('40', '40'), ('40hq', '40hq')], max_length=5)),
                ('exim', models.CharField(choices=[('Import', 'Import'), ('Export', 'Export')], max_length=10)),
                ('rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='api.port')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='api.port')),
            ],
        ),
    ]
