# Generated by Django 4.0.6 on 2022-08-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rates_exim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
