# Generated by Django 4.0.6 on 2022-08-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rates_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rates',
            name='created_by',
        ),
    ]
